name: Run Shell Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest  # 実行する環境（ここではUbuntu）

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # リポジトリをチェックアウト

      - name: Make shell script executable
        run: chmod +x .github/workflows/run_magicpod_test.sh  # .shファイルに実行権限を付与

      - name: Run the shell script
        run: .github/workflows/run_magicpod_test.sh  # シェルスクリプトを実行
