name: Manual          # ワークフロー名

on:
  workflow_dispatch:  # 手動実行イベント
    inputs:
      greeting:         # 入力パラメータ名
        type: choice      # データ型(文字列)
        options:
        - info
        - warn
        - error
        # default: Hello    # 入力パラメータのデフォルト値
        # required: true    # 入力パラメータの必須フラグ
        description: A cheerful word  # 入力パラメータの概要

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Development
        if: ${{ github.event.inputs.environment == 'info' }}
        run: |
          echo "Deploying to Development environment"
          # 実際のデプロイコマンドや処理を追加

      - name: Deploy to Staging
        if: ${{ github.event.inputs.environment == 'warn' }}
        run: |
          echo "Deploying to Staging environment"
          # 実際のデプロイコマンドや処理を追加

      - name: Deploy to Production
        if: ${{ github.event.inputs.environment == 'error' }}
        run: |
          echo "Deploying to Production environment"
          # 実際のデプロイコマンドや処理を追加